AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trac-app

  Application for Trac use case using Amazon Rekognition

Globals:
  Function:
    Timeout: 20
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  TracCustomLabelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TracCustomLabelFunction
      Handler: trac.TracCustomLabelFunction::handleRequest
      Runtime: java11
      Policies:
        - S3ReadPolicy:
            BucketName: '*trac*' #Update the parameter according to your bucket name
        - AmazonRekognitionCustomLabelsFullAccess
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          TRAC_REKOGNITION_CLASSIFY_ARN: VALUE
          TRAC_REKOGNITION_OBJECT_DETECTION_ARN: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        Trac:
          Type: Api
          Properties:
            Path: /customlabel
            Method: post


Outputs:
  TracClassificationApi:
    Description: "API Gateway endpoint URL for Prod stage for Trac Classification function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customlabel/"
  TracCustomLabelFunction:
    Description: "Trac Custom Label Lambda Function ARN"
    Value: !GetAtt TracCustomLabelFunction.Arn
  TracCustomLabelFunctionIamRole:
    Description: "Implicit IAM Role created for Trac Custom Label function"
    Value: !GetAtt TracCustomLabelFunctionRole.Arn
